# Steam games complete dataset
Analyzing the [Kaggle Dataset](https://www.kaggle.com/datasets/trolukovich/steam-games-complete-dataset) 
with information about Steam games

In [9]:
import numpy as np
import pandas as pd
import matplotlib
import re

In [10]:
ls /home/rogersimy/code/zxrey/Game-On-Project/raw_data/

steam_games.csv

In [11]:
file = "/home/rogersimy/code/zxrey/Game-On-Project/raw_data/steam_games.csv"
games_df = pd.read_csv(file)
games_df.head(3)

,url,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,game_details,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price
0,https://store.steampowered.com/app/379720/DOOM/,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...","Single-player,Multi-player,Co-op,Steam Achieve...","English,French,Italian,German,Spanish - Spain,...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",$19.99,$14.99
1,https://store.steampowered.com/app/578080/PLAY...,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...","Multi-player,Online Multi-Player,Stats","English,Korean,Simplified Chinese,French,Germa...",37.0,"Action,Adventure,Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$29.99,NaN
2,https://store.steampowered.com/app/637090/BATT...,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Single-player,Multi-player,Online Multi-Player...","English,French,German,Russian",128.0,"Action,Adventure,Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$39.99,NaN

In [12]:
games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40833 entries, 0 to 40832
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   url                       40833 non-null  object
 1   types                     40831 non-null  object
 2   name                      40817 non-null  object
 3   desc_snippet              27612 non-null  object
 4   recent_reviews            2706 non-null   object
 5   all_reviews               28470 non-null  object
 6   release_date              37654 non-null  object
 7   developer                 40490 non-null  object
 8   publisher                 35733 non-null  object
 9   popular_tags              37888 non-null  object
 10  game_details              40313 non-null  object
 11  languages                 40797 non-null  object
 12  achievements              12194 non-null  float64
 13  genre                     40395 non-null  object
 14  game_description          37920 non-null  object
 15  mature_content            2897 non-null   object
 16  minimum_requirements      21069 non-null  object
 17  recommended_requirements  21075 non-null  object
 18  original_price            35522 non-null  object
 19  discount_price            14543 non-null  object
dtypes: float64(1), object(19)
memory usage: 6.2+ MB

In [13]:
def extract_percentage(text):
    if not isinstance(text, str):
        return None  # or np.nan, or 0
    match = re.search(r'([-]?\d+)%', text)
    if match:
        return int(match.group(1))
    return None

In [14]:
games_df['review_percentage'] = games_df['recent_reviews'].apply(extract_percentage)

In [ ]:
games_df.head(3)

,url,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,...,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price,review_percentage
0,https://store.steampowered.com/app/379720/DOOM/,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...",...,"English,French,Italian,German,Spanish - Spain,...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",19.99,$14.99,89.0
1,https://store.steampowered.com/app/578080/PLAY...,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...",...,"English,Korean,Simplified Chinese,French,Germa...",37.0,"Action,Adventure,Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",29.99,NaN,49.0
2,https://store.steampowered.com/app/637090/BATT...,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...",...,"English,French,German,Russian",128.0,"Action,Adventure,Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",39.99,NaN,54.0

In [15]:
unique_values = games_df['review_percentage'].unique()
# For numeric values
sorted_unique_values = sorted(unique_values)

# For descending order
sorted_unique_values_desc = sorted(unique_values, reverse=True)
print(sorted_unique_values_desc)

[np.float64(nan), np.float64(100.0), np.float64(99.0), np.float64(98.0), np.float64(97.0), np.float64(96.0), np.float64(95.0), np.float64(94.0), np.float64(93.0), np.float64(92.0), np.float64(91.0), np.float64(90.0), np.float64(89.0), np.float64(88.0), np.float64(87.0), np.float64(86.0), np.float64(85.0), np.float64(84.0), np.float64(83.0), np.float64(82.0), np.float64(81.0), np.float64(80.0), np.float64(79.0), np.float64(78.0), np.float64(77.0), np.float64(76.0), np.float64(75.0), np.float64(74.0), np.float64(73.0), np.float64(72.0), np.float64(71.0), np.float64(70.0), np.float64(69.0), np.float64(68.0), np.float64(67.0), np.float64(66.0), np.float64(65.0), np.float64(64.0), np.float64(63.0), np.float64(62.0), np.float64(61.0), np.float64(60.0), np.float64(59.0), np.float64(58.0), np.float64(57.0), np.float64(56.0), np.float64(55.0), np.float64(54.0), np.float64(53.0), np.float64(52.0), np.float64(51.0), np.float64(50.0), np.float64(49.0), np.float64(48.0), np.float64(47.0), np.float64(46.0), np.float64(45.0), np.float64(44.0), np.float64(43.0), np.float64(42.0), np.float64(41.0), np.float64(40.0), np.float64(39.0), np.float64(38.0), np.float64(37.0), np.float64(36.0), np.float64(35.0), np.float64(34.0), np.float64(33.0), np.float64(32.0), np.float64(31.0), np.float64(30.0), np.float64(29.0), np.float64(28.0), np.float64(27.0), np.float64(26.0), np.float64(25.0), np.float64(24.0), np.float64(23.0), np.float64(20.0), np.float64(18.0), np.float64(16.0), np.float64(15.0), np.float64(14.0), np.float64(12.0), np.float64(11.0), np.float64(10.0), np.float64(8.0), np.float64(7.0), np.float64(0.0)]

In [16]:
# Assuming your DataFrame is named games_df and the column is 'original_price'

# Step 1: Replace 'Free' and '0' with '0'
games_df['original_price'] = games_df['original_price'].replace({'Free': '0', '0': '0'})

# Step 2: Remove dollar signs
games_df['original_price'] = games_df['original_price'].astype(str).str.replace('$', '', regex=False)

# Step 3: Convert to float, coercing errors to NaN
games_df['original_price'] = pd.to_numeric(games_df['original_price'], errors='coerce')

# Optional: fill NaN values with 0.0 if needed
games_df['original_price'] = games_df['original_price'].fillna(0.0)

In [23]:
formatted_unique_values = [f"{val:.2f}" for val in unique_values]
# For descending order
sorted_formatted_unique_values_desc = sorted(formatted_unique_values, reverse=True)
print(sorted_formatted_unique_values_desc)

['nan', '99.00', '98.00', '97.00', '96.00', '95.00', '94.00', '93.00', '92.00', '91.00', '90.00', '89.00', '88.00', '87.00', '86.00', '85.00', '84.00', '83.00', '82.00', '81.00', '80.00', '8.00', '79.00', '78.00', '77.00', '76.00', '75.00', '74.00', '73.00', '72.00', '71.00', '70.00', '7.00', '69.00', '68.00', '67.00', '66.00', '65.00', '64.00', '63.00', '62.00', '61.00', '60.00', '59.00', '58.00', '57.00', '56.00', '55.00', '54.00', '53.00', '52.00', '51.00', '50.00', '49.00', '48.00', '47.00', '46.00', '45.00', '44.00', '43.00', '42.00', '41.00', '40.00', '39.00', '38.00', '37.00', '36.00', '35.00', '34.00', '33.00', '32.00', '31.00', '30.00', '29.00', '28.00', '27.00', '26.00', '25.00', '24.00', '23.00', '20.00', '18.00', '16.00', '15.00', '14.00', '12.00', '11.00', '100.00', '10.00', '0.00']

In [18]:
games_df['genre'] = games_df['genre'].str.replace(',', ', ', regex=False)

In [19]:
games_df.head(3)

,url,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,...,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price,review_percentage
0,https://store.steampowered.com/app/379720/DOOM/,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...",...,"English,French,Italian,German,Spanish - Spain,...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",19.99,$14.99,89.0
1,https://store.steampowered.com/app/578080/PLAY...,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...",...,"English,Korean,Simplified Chinese,French,Germa...",37.0,"Action, Adventure, Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",29.99,NaN,49.0
2,https://store.steampowered.com/app/637090/BATT...,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...",...,"English,French,German,Russian",128.0,"Action, Adventure, Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",39.99,NaN,54.0

In [20]:
counts = games_df['original_price'].value_counts()
# Para mostrar en forma de tabla, puedes convertirlo en DataFrame
counts_df = counts.reset_index()
counts_df.columns = ['Value', 'Count']
print(counts_df)

      Value  Count
0      0.00   8329
1      4.99   4123
2      9.99   3903
3      0.99   3569
4      2.99   3371
..      ...    ...
430  149.00      1
431  229.98      1
432  749.00      1
433  999.00      1
434    1.09      1

[435 rows x 2 columns]

In [ ]:
counts_df = counts_df.sort_values(by='Count', ascending=False)
print(counts_df)

      Value  Count
0      0.00   8329
1      4.99   4123
2      9.99   3903
3      0.99   3569
4      2.99   3371
..      ...    ...
398    5.95      1
399  189.94      1
400   33.99      1
401  203.95      1
434    1.09      1

[435 rows x 2 columns]

In [21]:
games_df['popular_tags'] = games_df['popular_tags'].str.replace(',', ', ', regex=False)

In [22]:
games_df['languages'] = games_df['languages'].str.replace(',', ', ', regex=False)

In [26]:
games_df.head(3)

,url,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,...,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price,review_percentage
0,https://store.steampowered.com/app/379720/DOOM/,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS, Gore, Action, Demons, Shooter, First-Pers...",...,"English, French, Italian, German, Spanish - Sp...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",19.99,$14.99,89.0
1,https://store.steampowered.com/app/578080/PLAY...,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival, Shooter, Multiplayer, Battle Royale,...",...,"English, Korean, Simplified Chinese, French, G...",37.0,"Action, Adventure, Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",29.99,NaN,49.0
2,https://store.steampowered.com/app/637090/BATT...,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs, Strategy, Turn-Based, Turn-Based Tactic...",...,"English, French, German, Russian",128.0,"Action, Adventure, Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",39.99,NaN,54.0

In [28]:
import re

def clean_description(text):
    # Remove encoding artifacts and special characters
    text = re.sub(r"[â€™‘’“”\"'*_]", '', text)
    # Remove asterisks, extra spaces, and newlines
    text = re.sub(r"\*+|\s+", ' ', text)
    # Convert to lowercase for normalization
    text = text.lower()
    # Strip leading/trailing whitespace
    return text.strip()

# Apply cleaning to your 'game_description' column
games_df['game_description'] = games_df['game_description'].astype(str)
games_df['cleaned_description'] = games_df['game_description'].apply(clean_description)

In [30]:
import re

def extract_year(text):
    if not isinstance(text, str):
        return None
    matches = re.findall(r'\d{4}', text)
    if matches:
        return matches[0]  # or use matches[-1] for last occurrence
    return None

# Apply to your DataFrame
games_df['release_year'] = games_df['release_date'].apply(extract_year)

In [32]:
games_df.head(100)

,url,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,...,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price,review_percentage,cleaned_description,release_year
0,https://store.steampowered.com/app/379720/DOOM/,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS, Gore, Action, Demons, Shooter, First-Pers...",...,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",19.99,$14.99,89.0,"about this game developed by id software, the ...",2016
1,https://store.steampowered.com/app/578080/PLAY...,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival, Shooter, Multiplayer, Battle Royale,...",...,"Action, Adventure, Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",29.99,NaN,49.0,about this game playerunknowns battlegrounds i...,2017
2,https://store.steampowered.com/app/637090/BATT...,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs, Strategy, Turn-Based, Turn-Based Tactic...",...,"Action, Adventure, Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",39.99,NaN,54.0,about this game from original battletech/mechw...,2018
3,https://store.steampowered.com/app/221100/DayZ/,app,DayZ,The post-soviet country of Chernarus is struck...,"Mixed,(932),- 57% of the 932 user reviews in t...","Mixed,(167,115),- 61% of the 167,115 user revi...","Dec 13, 2018",Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","Survival, Zombies, Open World, Multiplayer, Pv...",...,"Action, Adventure, Massively Multiplayer",About This Game The post-soviet country of Ch...,NaN,"Minimum:,OS:,Windows 7/8.1 64-bit,Processor:,I...","Recommended:,OS:,Windows 10 64-bit,Processor:,...",44.99,NaN,57.0,about this game the post-soviet country of che...,2018
4,https://store.steampowered.com/app/8500/EVE_On...,app,EVE Online,EVE Online is a community-driven spaceship MMO...,"Mixed,(287),- 54% of the 287 user reviews in t...","Mostly Positive,(11,481),- 74% of the 11,481 u...","May 6, 2003",CCP,"CCP,CCP","Space, Massively Multiplayer, Sci-fi, Sandbox,...",...,"Action, Free to Play, Massively Multiplayer, R...",About This Game,NaN,"Minimum:,OS:,Windows 7,Processor:,Intel Dual C...","Recommended:,OS:,Windows 10,Processor:,Intel i...",0.00,NaN,54.0,about this game,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,https://store.steampowered.com/app/227940/Hero...,app,Heroes & Generals,"Shoot, blow sh!t up, fly or bark orders in the...","Mixed,(906),- 56% of the 906 user reviews in t...","Mixed,(101,309),- 65% of the 101,309 user revi...","Oct 18, 2016",RETO MOTO,"RETO MOTO,RETO MOTO","Free to Play, World War II, FPS, Multiplayer, ...",...,"Action, Free to Play, Indie, Massively Multipl...",About This Game Heroes & Generals is a full ...,NaN,"Minimum:,OS:,Windows 7 and up,Processor:,2GHz ...","Recommended:,OS:,Windows 10 x64,Processor:,Int...",0.00,NaN,56.0,about this game heroes & generals is a full on...,2016
96,https://store.steampowered.com/app/2280/Ultima...,app,Ultimate Doom,The complete megahit game that set the world a...,"Very Positive,(70),- 92% of the 70 user review...","Very Positive,(3,511),- 93% of the 3,511 user ...","Apr 30, 1995",id Software,"id Software,id Software","Classic, FPS, Action, 1990's, Great Soundtrack...",...,Action,About This Game The complete megahit game tha...,NaN,NaN,NaN,14.99,$7.49,92.0,about this game the complete megahit game that...,1995
97,https://store.steampowered.com/app/578620/GORN/,app,GORN,GORN is a ludicrously violent VR gladiator sim...,"Very Positive,(67),- 94% of the 67 user review...","Overwhelmingly Positive,(3,286),- 96% of the 3...","Jul 10, 2017",Free Lives,"Devolver Digital,Devolver Digital","Early Access, VR, Violent, Gore, Early Access,...",...,"Action, Indie, Early Access",About This Game GORN is a ludicrously violent...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",19.99,$169.92,94.0,about this game gorn is a ludicrously violent ...,2017
98,https://store.steampowered.com/app/678950/DRAG...,app,DRAGON BALL FighterZ,DRAGON BALL FighterZ is born from what makes t...,"Mostly Positive,(131),- 76% of the 131 user re...","Very Positive,(8,966),- 82% of the 8,966 user ...","Jan 26, 2018",Arc System Works,"BANDAI NAMCO Entertainment,BANDAI NAMCO Entert...","Fighting, Anime, 2D Fighter, Multiplayer, Acti...",...,Action,About This Game DRAGON BALL FighterZ is born...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",59.99,NaN,76.0,about this game dragon ball fighterz is born f...,2018
99,https://store.steampowered.com/app/252690/Fant...,app,Fantasy Grounds,Fantasy Grounds is a hybrid application which ...,"Very Positive,(11),- 81% of the 11 user review...","Mostly Positive,(381),- 75% of the 381 user re...","May 9, 2014","SmiteWorks USA, LLC","SmiteWorks USA, LLC,SmiteWorks USA, LLC","RPG, Strategy, Software, Indie, Turn-Based, Fa...",...,"Indie, RPG, Strategy",About This Game Fantasy Grounds is an applica...,NaN,"Minimum:,OS:,Windows 7, Windows 8 or Windows 1...","Recommended:,OS:,Windows 7 or Windows 8,Proces...",7.99,$145.14,81.0,about this game fantasy grounds is an applicat...,2014