In [2]:
import numpy as np
import pandas as pd

In [27]:
df = pd.read_csv("/mnt/c/Users/Usuario/Downloads/steam_games.csv")
df.head(8)

,url,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,game_details,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price
0,https://store.steampowered.com/app/379720/DOOM/,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...","Single-player,Multi-player,Co-op,Steam Achieve...","English,French,Italian,German,Spanish - Spain,...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",$19.99,$14.99
1,https://store.steampowered.com/app/578080/PLAY...,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...","Multi-player,Online Multi-Player,Stats","English,Korean,Simplified Chinese,French,Germa...",37.0,"Action,Adventure,Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$29.99,NaN
2,https://store.steampowered.com/app/637090/BATT...,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Single-player,Multi-player,Online Multi-Player...","English,French,German,Russian",128.0,"Action,Adventure,Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$39.99,NaN
3,https://store.steampowered.com/app/221100/DayZ/,app,DayZ,The post-soviet country of Chernarus is struck...,"Mixed,(932),- 57% of the 932 user reviews in t...","Mixed,(167,115),- 61% of the 167,115 user revi...","Dec 13, 2018",Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","Survival,Zombies,Open World,Multiplayer,PvP,Ma...","Multi-player,Online Multi-Player,Steam Worksho...","English,French,Italian,German,Spanish - Spain,...",NaN,"Action,Adventure,Massively Multiplayer",About This Game The post-soviet country of Ch...,NaN,"Minimum:,OS:,Windows 7/8.1 64-bit,Processor:,I...","Recommended:,OS:,Windows 10 64-bit,Processor:,...",$44.99,NaN
4,https://store.steampowered.com/app/8500/EVE_On...,app,EVE Online,EVE Online is a community-driven spaceship MMO...,"Mixed,(287),- 54% of the 287 user reviews in t...","Mostly Positive,(11,481),- 74% of the 11,481 u...","May 6, 2003",CCP,"CCP,CCP","Space,Massively Multiplayer,Sci-fi,Sandbox,MMO...","Multi-player,Online Multi-Player,MMO,Co-op,Onl...","English,German,Russian,French",NaN,"Action,Free to Play,Massively Multiplayer,RPG,...",About This Game,NaN,"Minimum:,OS:,Windows 7,Processor:,Intel Dual C...","Recommended:,OS:,Windows 10,Processor:,Intel i...",Free,NaN
5,https://store.steampowered.com/bundle/5699/Gra...,bundle,Grand Theft Auto V: Premium Online Edition,Grand Theft Auto V: Premium Online Edition bundle,NaN,NaN,NaN,Rockstar North,Rockstar Games,NaN,"Single-player,Multi-player,Downloadable Conten...","English, French, Italian, German, Spanish - Sp...",NaN,"Action,Adventure",NaN,NaN,NaN,NaN,NaN,$35.18
6,https://store.steampowered.com/app/601150/Devi...,app,Devil May Cry 5,"The ultimate Devil Hunter is back in style, in...","Very Positive,(408),- 87% of the 408 user revi...","Very Positive,(9,645),- 92% of the 9,645 user ...","Mar 7, 2019","CAPCOM Co., Ltd.","CAPCOM Co., Ltd.,CAPCOM Co., Ltd.","Action,Hack and Slash,Great Soundtrack,Demons,...","Single-player,Online Multi-Player,Online Co-op...","English,French,Italian,German,Spanish - Spain,...",51.0,Action,About This Game The Devil you know returns in...,Mature Content Description The developers de...,"Minimum:,OS:,WINDOWS® 7, 8.1, 10 (64-BIT Requi...","Recommended:,OS:,WINDOWS® 7, 8.1, 10 (64-BIT R...",$59.99,$70.42
7,https://store.steampowered.com/app/477160/Huma...,app,Human: Fall Flat,Human: Fall Flat is a quirky open-ended physic...,"Very Positive,(629),- 91% of the 629 user revi...","Very Positive,(23,763),- 91% of the 23,763 use...","Jul 22, 2016",No Brakes Games,"Curve Digital,Curve Digital","Funny,Multiplayer,Co-op,Puzzle,Physics,Local C...","Single-player,Online Multi-Player,Local Co-op,...","English,French,German,Spanish - Spain,Russian,...",55.0,"Adventure,Indie","About This Game ***NEW ""DARK"" LEVEL AVAILABL...",NaN,"Minimum:,OS:,Windows XP/Vista/7/8/8.1/10 x86 a...","Recommended:,OS:,Windows XP/Vista/7/8/8.1/10 x...",$14.99,$17.58

In [30]:
games_df = df

In [34]:
# Step 1: Replace 'Free' and '0' with '0'
games_df['original_price'] = games_df['original_price'].replace({'Free': '0', '0': '0'})

# Step 2: Remove dollar signs
games_df['original_price'] = games_df['original_price'].astype(str).str.replace('$', '', regex=False)

# Step 3: Convert to float, coercing errors to NaN
games_df['original_price'] = pd.to_numeric(games_df['original_price'], errors='coerce')

# Optional: fill NaN values with 0.0 if needed
games_df['original_price'] = games_df['original_price'].fillna(0.0)

In [10]:
df['release_date'].isna().sum()

np.int64(3179)

In [84]:
# Elimina filas que no contienen un año de 4 dígitos (TBA, TBD, Coming Soon, etc.)
df = df[df['release_date'].str.contains(r'\d{4}', na=False)]

# Maneja casos como '20180108' convirtiéndolos a '2018', luego toma el último año en casos como '2019/2020'
df['release_date'] = df['release_date'].str.replace(r'(\d{4})\d{4}', r'\1', regex=True).str.findall(r'\d{4}').str[-1]

# Extrae el último grupo de 4 dígitos como año final
df['release_date'] = df['release_date'].str.extract(r'(\d{4})(?!.*\d{4})')

# Convierte el año a tipo entero
df['release_date'] = df['release_date'].astype(int)

In [85]:
df['release_date'].isna().sum()

np.int64(0)

In [7]:
from IPython.display import display, HTML
display(HTML(f"<p style='width:600px; word-wrap:break-word;'>{df['game_description'].iloc[0]}</p>"))

In [72]:
# Convierte el año a tipo entero
df['release_date'] = df['release_date'].astype(int)

In [73]:
df

,url,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,game_details,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price
0,https://store.steampowered.com/app/379720/DOOM/,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...",1451606400000000000,id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...","Single-player,Multi-player,Co-op,Steam Achieve...","English,French,Italian,German,Spanish - Spain,...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",$19.99,$14.99
1,https://store.steampowered.com/app/578080/PLAY...,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...",1483228800000000000,PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...","Multi-player,Online Multi-Player,Stats","English,Korean,Simplified Chinese,French,Germa...",37.0,"Action,Adventure,Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$29.99,NaN
2,https://store.steampowered.com/app/637090/BATT...,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...",1514764800000000000,Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Single-player,Multi-player,Online Multi-Player...","English,French,German,Russian",128.0,"Action,Adventure,Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$39.99,NaN
3,https://store.steampowered.com/app/221100/DayZ/,app,DayZ,The post-soviet country of Chernarus is struck...,"Mixed,(932),- 57% of the 932 user reviews in t...","Mixed,(167,115),- 61% of the 167,115 user revi...",1514764800000000000,Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","Survival,Zombies,Open World,Multiplayer,PvP,Ma...","Multi-player,Online Multi-Player,Steam Worksho...","English,French,Italian,German,Spanish - Spain,...",NaN,"Action,Adventure,Massively Multiplayer",About This Game The post-soviet country of Ch...,NaN,"Minimum:,OS:,Windows 7/8.1 64-bit,Processor:,I...","Recommended:,OS:,Windows 10 64-bit,Processor:,...",$44.99,NaN
4,https://store.steampowered.com/app/8500/EVE_On...,app,EVE Online,EVE Online is a community-driven spaceship MMO...,"Mixed,(287),- 54% of the 287 user reviews in t...","Mostly Positive,(11,481),- 74% of the 11,481 u...",1041379200000000000,CCP,"CCP,CCP","Space,Massively Multiplayer,Sci-fi,Sandbox,MMO...","Multi-player,Online Multi-Player,MMO,Co-op,Onl...","English,German,Russian,French",NaN,"Action,Free to Play,Massively Multiplayer,RPG,...",About This Game,NaN,"Minimum:,OS:,Windows 7,Processor:,Intel Dual C...","Recommended:,OS:,Windows 10,Processor:,Intel i...",Free,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40828,https://store.steampowered.com/app/899836/Rock...,app,Rocksmith® 2014 Edition – Remastered – Sabaton...,NaN,NaN,NaN,1546300800000000000,Ubisoft - San Francisco,NaN,"Casual,Simulation","Single-player,Shared/Split Screen,Downloadable...","English,German,French,Italian,Spanish - Spain,...",NaN,"Casual,Simulation","About This Content Play ""Ghost Division"" by S...",NaN,"Minimum:,OS:,Windows Vista, Windows 7, Windows...","Recommended:,OS:,Windows Vista, Windows 7, Win...",$2.99,NaN
40829,https://store.steampowered.com/app/899832/Rock...,app,Rocksmith® 2014 Edition – Remastered – Stone T...,NaN,NaN,NaN,1546300800000000000,Ubisoft - San Francisco,NaN,"Casual,Simulation","Single-player,Shared/Split Screen,Downloadable...","English,German,French,Italian,Spanish - Spain,...",NaN,"Casual,Simulation","About This Content Play ""Trippin’ on a Hole i...",NaN,"Minimum:,OS:,Windows Vista, Windows 7, Windows...","Recommended:,OS:,Windows Vista, Windows 7, Win...",$2.99,NaN
40830,https://store.steampowered.com/app/906840/Fant...,app,Fantasy Grounds - Quests of Doom 4: A Midnight...,NaN,NaN,NaN,1514764800000000000,"SmiteWorks USA, LLC",NaN,"RPG,Indie,Strategy,Software,Turn-Based,Fantasy...","Multi-player,Co-op,Cross-Platform Multiplayer,...",English,NaN,"Indie,RPG,Strategy",About This Content Quests of Doom 4: A Midni...,NaN,"Minimum:,OS:,Windows 7x , 8x or 10x,Processor:...","Recommended:,OS:,Windows 7x , 8x or 10x,Proces...",$7.99,NaN
40831,https://store.steampowered.com/app/906635/Mega...,app,Mega Man X5 Sound Collection,NaN,NaN,NaN,1514764800000000000,"CAPCOM CO., LTD","CAPCOM CO., LTD,CAPCOM CO., LTD",Action,"Single-player,Downloadable Content,Steam Achie...","English,French,Italian,German,Spanish - Spain,...",NaN,Action,About This Content Get equipped with the stun...,NaN,"Minimum:,OS:,WINDOWS® 7 (64bit),Processor:,Int...","Recommended:,OS:,WINDOWS®10 (64bit),Processor:...",$9.99,NaN
40832,https://store.steampowered.com/app/908000/Stor...,app,Stories In Stone,An RPG about a tribe exploring an ancient worl...,NaN,NaN,1514764800000000000,"16 Bit Psych,Kyle B","Self-Publish,Self-Publish","RPG,Adventure","Single-player,Partial Controller Support,Profi...",English,NaN,"Adventure,RPG",About This Game An RPG about a tribe explori...,NaN,NaN,NaN,$4.99,$2.80

array([], dtype=object)

In [65]:
df

,url,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,game_details,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price
0,https://store.steampowered.com/app/379720/DOOM/,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...",2016-01-01,id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...","Single-player,Multi-player,Co-op,Steam Achieve...","English,French,Italian,German,Spanish - Spain,...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",$19.99,$14.99
1,https://store.steampowered.com/app/578080/PLAY...,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...",2017-01-01,PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...","Multi-player,Online Multi-Player,Stats","English,Korean,Simplified Chinese,French,Germa...",37.0,"Action,Adventure,Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$29.99,NaN
2,https://store.steampowered.com/app/637090/BATT...,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...",2018-01-01,Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Single-player,Multi-player,Online Multi-Player...","English,French,German,Russian",128.0,"Action,Adventure,Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$39.99,NaN
3,https://store.steampowered.com/app/221100/DayZ/,app,DayZ,The post-soviet country of Chernarus is struck...,"Mixed,(932),- 57% of the 932 user reviews in t...","Mixed,(167,115),- 61% of the 167,115 user revi...",2018-01-01,Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","Survival,Zombies,Open World,Multiplayer,PvP,Ma...","Multi-player,Online Multi-Player,Steam Worksho...","English,French,Italian,German,Spanish - Spain,...",NaN,"Action,Adventure,Massively Multiplayer",About This Game The post-soviet country of Ch...,NaN,"Minimum:,OS:,Windows 7/8.1 64-bit,Processor:,I...","Recommended:,OS:,Windows 10 64-bit,Processor:,...",$44.99,NaN
4,https://store.steampowered.com/app/8500/EVE_On...,app,EVE Online,EVE Online is a community-driven spaceship MMO...,"Mixed,(287),- 54% of the 287 user reviews in t...","Mostly Positive,(11,481),- 74% of the 11,481 u...",2003-01-01,CCP,"CCP,CCP","Space,Massively Multiplayer,Sci-fi,Sandbox,MMO...","Multi-player,Online Multi-Player,MMO,Co-op,Onl...","English,German,Russian,French",NaN,"Action,Free to Play,Massively Multiplayer,RPG,...",About This Game,NaN,"Minimum:,OS:,Windows 7,Processor:,Intel Dual C...","Recommended:,OS:,Windows 10,Processor:,Intel i...",Free,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40828,https://store.steampowered.com/app/899836/Rock...,app,Rocksmith® 2014 Edition – Remastered – Sabaton...,NaN,NaN,NaN,2019-01-01,Ubisoft - San Francisco,NaN,"Casual,Simulation","Single-player,Shared/Split Screen,Downloadable...","English,German,French,Italian,Spanish - Spain,...",NaN,"Casual,Simulation","About This Content Play ""Ghost Division"" by S...",NaN,"Minimum:,OS:,Windows Vista, Windows 7, Windows...","Recommended:,OS:,Windows Vista, Windows 7, Win...",$2.99,NaN
40829,https://store.steampowered.com/app/899832/Rock...,app,Rocksmith® 2014 Edition – Remastered – Stone T...,NaN,NaN,NaN,2019-01-01,Ubisoft - San Francisco,NaN,"Casual,Simulation","Single-player,Shared/Split Screen,Downloadable...","English,German,French,Italian,Spanish - Spain,...",NaN,"Casual,Simulation","About This Content Play ""Trippin’ on a Hole i...",NaN,"Minimum:,OS:,Windows Vista, Windows 7, Windows...","Recommended:,OS:,Windows Vista, Windows 7, Win...",$2.99,NaN
40830,https://store.steampowered.com/app/906840/Fant...,app,Fantasy Grounds - Quests of Doom 4: A Midnight...,NaN,NaN,NaN,2018-01-01,"SmiteWorks USA, LLC",NaN,"RPG,Indie,Strategy,Software,Turn-Based,Fantasy...","Multi-player,Co-op,Cross-Platform Multiplayer,...",English,NaN,"Indie,RPG,Strategy",About This Content Quests of Doom 4: A Midni...,NaN,"Minimum:,OS:,Windows 7x , 8x or 10x,Processor:...","Recommended:,OS:,Windows 7x , 8x or 10x,Proces...",$7.99,NaN
40831,https://store.steampowered.com/app/906635/Mega...,app,Mega Man X5 Sound Collection,NaN,NaN,NaN,2018-01-01,"CAPCOM CO., LTD","CAPCOM CO., LTD,CAPCOM CO., LTD",Action,"Single-player,Downloadable Content,Steam Achie...","English,French,Italian,German,Spanish - Spain,...",NaN,Action,About This Content Get equipped with the stun...,NaN,"Minimum:,OS:,WINDOWS® 7 (64bit),Processor:,Int...","Recommended:,OS:,WINDOWS®10 (64bit),Processor:...",$9.99,NaN
40832,https://store.steampowered.com/app/908000/Stor...,app,Stories In Stone,An RPG about a tribe exploring an ancient worl...,NaN,NaN,2018-01-01,"16 Bit Psych,Kyle B","Self-Publish,Self-Publish","RPG,Adventure","Single-player,Partial Controller Support,Profi...",English,NaN,"Adventure,RPG",About This Game An RPG about a tribe explori...,NaN,NaN,NaN,$4.99,$2.80

In [ ]:
df[~df['release_date'].str.contains(r'\d{4}', na=False)]['release_date'].unique()

array([], dtype=object)

In [38]:
df[~df['release_date'].str.match(r"^[A-Za-z]+ (\d+, )?\d{4}$", na=False)]['release_date'].unique()

array([nan, '20/06/2019', 'TBA', '2016', '2017',
       '2017 - Free During Early Access', 'TBD', 'July 26th, 2019',
       '2019', 'Q2 2019', 'Q3 2019', 'coming soon', 'Coming Soon',
       'Coming Soon 2019', '5/18/2018', '2020', '2Q 2018', 'Coming soon',
       'Coming soon™', 'August 1st, 2019', 'Q4 2019',
       "Coming When It's Ready", 'COMING SOON!', 'Coming soon!',
       "When it's done", 'Early Summer 2019',
       'Official Release Coming Soon! - Twitch Subscriber Builds available at twitch.tv/wheeze202',
       '2022', 'Pek Yakında', 'Spring - 2020', '2018',
       '2019 - add to wishlist!',
       '6 years after the Doomsday 2012 apocalypse', 'SOON', 'Q1/Q2 2020',
       'Sometime in 2020?',
       'O jogo está em desenvolvimento e pode ser lançado até o fim de 2019',
       'Coming soon 2019', 'Q1 2019', '08-2019',
       'In like, a couple of months probably.', 'Soon', '2021', 'July',
       'Q1 2020', 'Q4 - 2019', 'when its ready', 'Coming soon...',
       'One Day', '2019-2020 付费下载', 'By the end of 2019.',
       'AS SOON AS READY', 'Q1 - 2020', 'Definitely by March 2020',
       'July / August', '2019-ish', 'Loot Dropping Summer 2019',
       'Coming Soon | 2019 |', 'Winter', 'About a year',
       'Fall 2019 - Wishlist now!', '2019 - 2020', 'Soon!', 'Q2 2020',
       'Coming Soon!', 'Q3 2020', 'Once ready', '秋季', 'IN DEVELOPMENT',
       'Before Graduation', '2019.10', "When it's ready", '2019-2020',
       'As soon as you look away', 'Mid-2019',
       'June 2019, add to wishlist', 'Demo Coming in 2019',
       'Spring / Summer 2019', 'Join Our Beta!', 'Q1 2017', 'Summer',
       'Coming in 2019', 'At the moment in development, add to wishlist!',
       'Coming In 2019', 'Under Development', '2019年', 'Q4 2019/Q1 2020',
       'June 2019. Add us to wishlist!', 'COMING SOON',
       'Coming soon to Steam Early Access', 'Indefinitely Delayed',
       'To Be Announced.', 'Q1 - 2019', 'The storm is coming!',
       'Coming Soon...', 'This Summer', 'Unknown', 'Q1 (ish), 2017',
       'To Be Announced',
       'When what lurks beneath the surface becomes known.',
       'In Development', 'When it is ready', 'Late 2016 - Early 2017',
       'Free Alpha', '等我做完', '2019 Q3', 'Coming soon..', 'Sep. 2017',
       '2017 Q4', '2020 - TBA', "When it's finished", 'Sometime in 2019',
       '2019年7月', 'Wishlist to get notified!',
       'Before the Second Apocalypse', 'When its done',
       'Early Access in 2019', 'Summer, 2019', 'Q1 2018', '12 July 2019',
       'Grand opening in 2019!', 'When it is finished',
       'Coming This Summer',
       "Soon, who know? Maybe not. I wonder how long this message can be. Pretty long I guess. It's coming, don't worry. Just not now. Read the announcements to be up to date. Also Valve, I can't believe this has no max length...",
       'Coming soon...ish', "When It's Done", 'In arcades December 10',
       'First half 2019', '2017 Q1', 'releasing soon', '2019, TBA™!!!',
       'Q4 2020', 'TBC', 'Coming Soon - 2019', 'EA in 2019', '14 July',
       'Sorry, On Hold For Now', 'Comming Soon', '下一个春天到来之前', 'Real soon',
       '17 July 2019', 'In development', 'When We Are Ready', 'בקרוב',
       '4th July 2019', 'Q4 2017', 'To be announced', 'coming soon..',
       "When it's done!", 'Early Access Starting Soon!',
       'When airships fly', 'Demo is available now!', '21 Jun, 2017',
       'Eventually', '2019Winter', '20xx', 'Coming late 2017', 'Soon™',
       'End of 2019', 'Available before you Gnome it.',
       'Postponed until TFM release', 'Q2/Q3 2019', '2018年夏',
       'Eventually!', 'Before Midnight, sometime in 2019', 'This summer',
       'Release date TBC', '2019 SUMMER', 'Coming in 2018!',
       'Somewhere in brighter future', '快了，已经在做了', 'July 5th 2019',
       'Spring 2019 Wishlist Us', 'Autumn, 2019', 'Coming Fall, 2019',
       'Coming soon - October 2019', '2019 免费发布', '该DLC仅供众筹玩家激活',
       'Proximamente', 'Currently in Pre-Alpha', 'ON HOLD',
       '2019. Whishlist it to know for sure', "When It's Done, 2019",
       'join our discord to find out more', '2019-03-01', 'soon',
       '内容准备就绪后', 'Early Next Year', "When it's ready (2019)!",
       'Coming Soon in 2019', '¯\\_(ツ)_/¯', 'When its good and ready',
       'September', 'Spring', 'Summer/Fall 2019', '2019年冬',
       'Not yet available', 'Q2 2018 Early Access', 'Q4 2021',
       '💀 COMING SOON 💀', '20181201', '2019年秋', 'Spring - Summer 2018',
       'Coming Q3 2019', 'TBA - Join our Community Hub!',
       'When Yoltrund is complete', 'Before WW3', 'Only Demo Available',
       'Available 19.6.19', 'Early Access Q2 2019',
       'Coming to home video 2019', '25 July 2019', 'q3 2019',
       '拿来这个吸引眼球的都是弱智', 'As soon as we can.', '2019 Q2', 'Rising soon',
       'H2 2019', '2019? Follow this page to get news', '2019 Summer',
       'When the game is ready for release', 'Summer 2020? Winter 2020?',
       'LATE 2019 / EARLY 2020', '2Q 2019', 'Q3/Q4 2019',
       'time is subjective', 'Kickstarter Coming Soon', 'Coming Soon-ish',
       "(When) I'm ready!", 'Prepping for the release',
       'Coming soon-ish!', '2019ish', 'when weapons are beautiful enough',
       'Сентябрь 2019', 'Release Date TBA', 'H1 2019', 'SUMMER',
       'Eventually...', '2020 Q2', 'tba', "It's being made.",
       'Coming Soon to Early Access', '???',
       'In Pre-Alpha: To Be Announced', '2019. Wishlist Us',
       'Expected soon!', '17 june 2019', 'May 31st, 2019',
       'Coming Soon in 2019!', 'When ready.', 'JUNE, 2019(Pre-OBT)',
       'July 18th!', '2019 coming soon', 'To be determinated',
       'Please wait warmly', "When it's ready 2019", 'Demo Coming Soon',
       'To be Announced', 'Goating Soon', 'Eventually in 2019',
       'add to wishlist', 'Sooner than you think', '2020 銳意製作中',
       'Q4-2019', 'Download the Demo', 'Mid-Late 2019',
       'Closed Alpha June 2018', 'Coming this summer',
       'Summer 2019 - wishlist now!', '~2019', 'First half of 2019',
       '19年', 'End of year 2019', 'First Half of 2019', 'Early Q2 2019',
       'Soonish!', 'July - 2019', 'When the Animations are Finished',
       'Summer!', 'WORK IN PROGRESS', 'When Ready', 'Q3 2019 wishlist',
       'EM BREVE', '2019/2020'], dtype=object)

In [19]:
df[~df['original_price'].str.startswith('$', na=False)]['original_price'].unique()

array(['Free', nan, 'Free to Play', '1.020', 'Free To Play',
       'Demo Middle-earth™: Shadow of War™', 'Play for Free!',
       'Shadow of the Tomb Raider Free Trial',
       'FINAL FANTASY XV WINDOWS EDITION PLAYABLE DEMO', 'UNO', 'Demo',
       'CrossCode Demo', 'EmergeNYC Demo', 'SpeedRunners Party Mode',
       'Learn to Play Edition', 'Soundpad Demo',
       'Try the complete game for one hour for free:',
       'LudoNarraCon demo',
       'Note: Your saved progress will transfer to the full game, if purchased.',
       'Home Sweet Home Demo', 'The Black Watchmen Demo', 'Play Demo!',
       'Cat Quest Demo', 'Panoptic Demo', 'LudoNarraCon Demo',
       'Try our free demo!', 'Play demo for free',
       'Worbital: Online Demo', 'Dungeon Siege III Demo',
       'The Crew Trial', 'New Retro Arcade: Neon (Tech Demo)',
       'Castlevania: Lords of Shadow 2 Demo',
       'Build and test ships in sandbox. All saved designs transfer to the full version.',
       'Rodina Demo', 'Free Demo', 'Garrison: Archangel Free Demo',
       'Realpolitiks Demo', 'Salt Demo', 'Sunrider Academy Demo',
       'Unbox Demo',
       '"Better than a demo!" 2D Paintball - Online | Full F2P Multiplayer!',
       '🆓 Free test drives! 🈚', 'Install Demo', 'Hunting Simulator Demo',
       'Geneshift Free Edition', 'The Textorcist: Demo', 'Try it NOW!',
       'Experience Quasar Spectrum OS for Free', 'Super X Chess Demo',
       'Jumps Demo', 'Hello Charlotte EP1', 'Dont Knock Twice VR Demo',
       'Kaiju Big Battel Fighto Fantasy Demo', 'Cuboid Keeper Demo',
       'Play WARMACHINE: Tactics Demo', 'SoulHunt Demo',
       'Walkerman Prologue', 'Winds Of Trade Demo', 'DEMO', 'Free Movie',
       'eden* Demo', 'Download demo', "Let's Rock", 'Third-party',
       'The Norwood Suite Demo', '灰烬天国 UnconqueredCastle', 'Try Demo',
       'Try the demo', 'Play the Demo', 'Protonwar Demo',
       'Try the free demo:', 'A Case of Distrust Demo', 'Free Mod',
       'Just Get Through Demo', "A Bastard's Tale Demo",
       'Download Free Guest Edition', 'Demo version', '试玩版',
       'Download Demo', 'Free Demo ( ͡~ ͜ʖ ͡°)', 'Kokorogawari Demo',
       'Wisgr Demo', 'Draid Demo', 'Sanguine Sanctum Demo',
       '3DCoat Modding Tool Demo', 'Duped: The Theseus Demo',
       'Planets Under Attack Demo',
       'Rayon Riddles - Rise of the Goblin King Demo',
       'Unholy Heights Trial Version', 'Download Demo !', 'Sym Demo',
       'ROTii Demo', 'FREE EDITION', 'Try the Free Version', 'ViSP Demo',
       'Try before you buy!', 'LABEL', 'Sceal Demo', 'Woven the Demo',
       'Get a full, 14 day trial version', 'Bootleg Systems Demo',
       'Gerty Demo', 'Questro', 'Give it a swing!', 'Gorescript Demo',
       'Locomotion Demo', 'FREE DOWNLOAD', 'CHOP Demo', 'Penarium Demo',
       'Spaceman Sparkles 3 Demo',
       'Chuusotsu - 1st Graduation: Time After Time English Demo',
       'Visual Novel, Free', 'SoulSet Demo', 'RLR Demo',
       'Chapter I: The Cross-bearing Man', 'Install',
       'Playable demo of Upwards, Lonely Robot', 'Horizon Shift Demo',
       'YumeUtsutsu Re:Master demo', '650560', 'Try CUR3D Maker Edition',
       'Escape Legacy - Short Demo', 'Heroes of Legionwood Demo',
       "The Last Dream: Developer's Edition Demo",
       'Put on your Top Hat, twiddle your tache and get the Woolley Mountain Demo now!',
       'Vector Wave Demo', 'A Golden Wake - Demo',
       'Circuit Breakers Demo', 'AccuRC 2 Limited Demo', 'Inked - Demo',
       'Play Now', 'Koliseum Soccer VR Demo', 'Demo-version',
       'Infinium Strike Demo', 'Try it now!', 'MilitAnt Demo',
       'Catyph Demo', "Hunter's Legacy Demo", 'Qubicle Demo',
       'Try the Demo!', "Funtoon's World (Demo)", 'Fluffy Demo',
       'Crying is not Enough: Demo', 'The Apartment Demo', 'Statues Demo',
       'Play the free demo!', 'Defenders of Time Demo', 'Play Demo',
       'Play now for free', 'Arcane Raise - Aurora Novus', 'Towns Demo',
       'Confederate Express Demo', 'Pit of Evil Demo', 'Try Demo!',
       'Wild Arena Demo', 'Ramayana Demo', 'Justice: Fallen Clan Demo',
       'SpaceSys Demo', 'Pitchfork Demo', 'Handpass VR Demo',
       'dungeon,builder,simulation,construct,build,simulator,TD,地城,地牢,地下城,經營,模擬,建造,2D,indie,獨立,模拟,经营,策略,独立,塔防,管理,開放世界',
       'Horse Racing 2016 (Demo)', 'Hit The Hive DEMO',
       'Dual Gear Pre-Alpha Demo', 'Bug Battle Demo',
       'Cursed Mansion Demo', 'Guardians Of The Past Demo',
       'Fortune & Gloria Demo', 'Tank Brawl 2 Survival Mode',
       'Codename Nemesis Demo', 'Free Prologue', 'Download FREE Demo',
       'game', 'Star Shift - Demo', 'Human Pinball: Iceage Demo',
       'Free Version', 'Playable Demo', '免费试玩！', 'Demo - Lems',
       'Shipbreaker Demo', 'Download Demo (Language: Korean)',
       'FREE ALPHA DEMO!', 'Play the demo!', 'Angry Ball VR Demo',
       'Gravity Heroes Demo', 'Demo Aussie Battler Tanks', '免费体验！',
       'PROLOGUE', 'Space Battlecruiser Demo', 'Copperbell Demo',
       'Free demo', 'Protoype Demo', 'פיפוש - האודישן',
       'Road Rage Royale Demo',
       'Not convinced enough? Play Deadsiege demo',
       'The Sorrowvirus: A Faceless Short Story', 'Enigma Prison Beta',
       'Black Hole Hazard Demo', 'Funklift Demo',
       'Galactic Fighters Demo', "Pop Island - Let's Code  ( intuition )",
       'Try it out please', 'Free DEMO!', 'Four Realms Demo',
       'Quest of Souls Demo', 'Free Pre-Alpha', 'Try the free demo!',
       'Failed State Demo Version', 'Soulblight Demo', 'Patterna Demo',
       'Open Beta', 'Download PC Demo',
       'Please try out the demo before purchasing.',
       'INTERSTELLAR PRIME Pre-Alpha 0.1 Game Engine Demo',
       'Demo Version', '"Location Test" Demo', 'Faulty Apprentice Demo',
       'Super Dungeon Boy: Mega Fire Demo', 'Amiss 13: the Curse Demo',
       'FREE DEMO', 'PLAY WITH ME Demo', 'Laika 2.0 Demo', 'Try RJ free!',
       "Gaia's Melody: Echoed Melodies Demo", 'Storms of Shambhala Demo',
       '730640', 'Hailstorm Demo', 'Coffee Talk Demo', 'Dyadic Demo',
       'Play Demo for Free', 'Windows Prototype', 'Kickstarter Demo',
       'Shadow of the Mask DEMO', 'Play Free Demo',
       "Love, Money, Rock'n'Roll Demo", 'UnsacrificeVRDemo', 'Orbs Demo',
       'Play Rage in Peace Demo', 'TRY THE FREE DEMO!', 'Play',
       'Download the demo here!', 'Soulfire Beta',
       'Up to 30 minutes of gameplay!', 'Pre-Alpha Demo',
       'Eagle Island Demo', 'DCL - The Game (Early Demo)',
       'Sky Racket Demo', 'Play the Demo!', 'Now Available',
       'Enjoy the Demo today!', 'Arcade Spirits Demo'], dtype=object)

# Codigo Limpio

In [3]:
import numpy as np
import pandas as pd
import matplotlib
import re

In [3]:
file = "/mnt/c/Users/Usuario/Downloads/steam_games.csv"
df = pd.read_csv(file)

In [4]:
#Limpieza de 'recent_reviews'
def extract_percentage(text):
    if not isinstance(text, str):
        return None  # or np.nan, or 0
    match = re.search(r'([-]?\d+)%', text)
    if match:
        return int(match.group(1))
    return None

df['review_percentage'] = df['recent_reviews'].apply(extract_percentage)

In [5]:
# Se eliminan columnas que no son relevantes para el análisis:
df = df.drop(columns=['types', 'all_reviews','desc_snippet', 'recent_reviews', 'developer', 'publisher', 'achievements', 'mature_content', 'minimum_requirements', 'recommended_requirements', 'discount_price'])

In [6]:
# limpieza de 'genre'
df['genre'] = df['genre'].str.replace(',', ', ', regex=False)

In [7]:
# limpieza de 'popular_tags'
df['popular_tags'] = df['popular_tags'].str.replace(',', ', ', regex=False)

In [8]:
# limpieza de 'game_details'
df['game_details'] = df['game_details'].str.replace(',', ', ', regex=False)

In [9]:
# limpieza de 'popular_tags'
df['languages'] = df['languages'].str.replace(',', ', ', regex=False)

In [10]:
#Limpieza de la columna 'release_date'
# Elimina filas que no contienen un año de 4 dígitos (TBA, TBD, Coming Soon, etc.)
df = df[df['release_date'].str.contains(r'\d{4}', na=False)]

# Maneja casos como '20180108' convirtiéndolos a '2018', luego toma el último año en casos como '2019/2020'
df['release_date'] = df['release_date'].str.replace(r'(\d{4})\d{4}', r'\1', regex=True).str.findall(r'\d{4}').str[-1]

# Extrae el último grupo de 4 dígitos como año final
df['release_date'] = df['release_date'].str.extract(r'(\d{4})(?!.*\d{4})')

# Convierte el año a tipo entero
df['release_date'] = df['release_date'].astype(int)

In [11]:
#df['game_description'] = df['game_description'].str.replace('about this game|about this content', '', case=False, regex=True).str.strip()


def clean_text(text):
    if pd.isna(text):
        return text
    text = re.sub(r"\*+|\s+", ' ', text)
    text = text.lower()
    return text.strip()

df['game_description'] = df['game_description'].apply(clean_text)

In [12]:
#Limpieza de la columna 'original_price'
# Step 1: Replace 'Free' and '0' with '0'
df['original_price'] = df['original_price'].replace({'Free': '0', '0': '0'})

# Step 2: Remove dollar signs
df['original_price'] = df['original_price'].astype(str).str.replace('$', '', regex=False)

# Step 3: Convert to float, coercing errors to NaN
df['original_price'] = pd.to_numeric(df['original_price'], errors='coerce')

# Optional: fill NaN values with 0.0 if needed
df['original_price'] = df['original_price'].fillna(0.0)

In [13]:
# Extrae el ID numérico del juego desde la URL de Steam
df['url']=df['url'].str.extract(r'/app/(\d+)/')

In [14]:
df['review_percentage'] = df['review_percentage'].apply(lambda x: f"Porcentaje de recomendación de jugadores: {int(x)}%" if pd.notna(x) else x)

In [15]:
df['popular_tags'] = df['popular_tags'].apply(lambda x: f"Tags populares: {x}" if pd.notna(x) else x)

In [16]:
df['game_details'] = df['game_details'].apply(lambda x: f"Tags populares: {x}" if pd.notna(x) else x)

In [17]:
df['genre'] = df['genre'].apply(lambda x: f"Genero de juego: {x}" if pd.notna(x) else x)

In [18]:
df['embedding'] = (
    df['game_description'] + '\n' +
    df['genre'] + '\n' +
    df['popular_tags'] + '\n' +
    df['game_details'] + '\n' +
    df['review_percentage']
)

In [19]:
df

,url,name,release_date,popular_tags,game_details,languages,genre,game_description,original_price,review_percentage,embedding
0,379720,DOOM,2016,"Tags populares: FPS, Gore, Action, Demons, Sho...","Tags populares: Single-player, Multi-player, C...","English, French, Italian, German, Spanish - Sp...",Genero de juego: Action,"about this game developed by id software, the ...",19.99,Porcentaje de recomendación de jugadores: 89%,"about this game developed by id software, the ..."
1,578080,PLAYERUNKNOWN'S BATTLEGROUNDS,2017,"Tags populares: Survival, Shooter, Multiplayer...","Tags populares: Multi-player, Online Multi-Pla...","English, Korean, Simplified Chinese, French, G...","Genero de juego: Action, Adventure, Massively ...",about this game playerunknown's battlegrounds ...,29.99,Porcentaje de recomendación de jugadores: 49%,about this game playerunknown's battlegrounds ...
2,637090,BATTLETECH,2018,"Tags populares: Mechs, Strategy, Turn-Based, T...","Tags populares: Single-player, Multi-player, O...","English, French, German, Russian","Genero de juego: Action, Adventure, Strategy",about this game from original battletech/mechw...,39.99,Porcentaje de recomendación de jugadores: 54%,about this game from original battletech/mechw...
3,221100,DayZ,2018,"Tags populares: Survival, Zombies, Open World,...","Tags populares: Multi-player, Online Multi-Pla...","English, French, Italian, German, Spanish - Sp...","Genero de juego: Action, Adventure, Massively ...",about this game the post-soviet country of che...,44.99,Porcentaje de recomendación de jugadores: 57%,about this game the post-soviet country of che...
4,8500,EVE Online,2003,"Tags populares: Space, Massively Multiplayer, ...","Tags populares: Multi-player, Online Multi-Pla...","English, German, Russian, French","Genero de juego: Action, Free to Play, Massive...",about this game,0.00,Porcentaje de recomendación de jugadores: 54%,"about this game\nGenero de juego: Action, Free..."
...,...,...,...,...,...,...,...,...,...,...,...
40828,899836,Rocksmith® 2014 Edition – Remastered – Sabaton...,2019,"Tags populares: Casual, Simulation","Tags populares: Single-player, Shared/Split Sc...","English, German, French, Italian, Spanish - Sp...","Genero de juego: Casual, Simulation","about this content play ""ghost division"" by sa...",2.99,NaN,NaN
40829,899832,Rocksmith® 2014 Edition – Remastered – Stone T...,2019,"Tags populares: Casual, Simulation","Tags populares: Single-player, Shared/Split Sc...","English, German, French, Italian, Spanish - Sp...","Genero de juego: Casual, Simulation","about this content play ""trippin’ on a hole in...",2.99,NaN,NaN
40830,906840,Fantasy Grounds - Quests of Doom 4: A Midnight...,2018,"Tags populares: RPG, Indie, Strategy, Software...","Tags populares: Multi-player, Co-op, Cross-Pla...",English,"Genero de juego: Indie, RPG, Strategy",about this content quests of doom 4: a midnigh...,7.99,NaN,NaN
40831,906635,Mega Man X5 Sound Collection,2018,Tags populares: Action,"Tags populares: Single-player, Downloadable Co...","English, French, Italian, German, Spanish - Sp...",Genero de juego: Action,about this content get equipped with the stunn...,9.99,NaN,NaN
40832,908000,Stories In Stone,2018,"Tags populares: RPG, Adventure","Tags populares: Single-player, Partial Control...",English,"Genero de juego: Adventure, RPG",about this game an rpg about a tribe exploring...,4.99,NaN,NaN

# codigo merge

In [63]:
df1 = pd.read_csv("/mnt/c/Users/Usuario/Downloads/applications.csv")

/tmp/ipykernel_2232/2881062485.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("/mnt/c/Users/Usuario/Downloads/applications.csv")

In [25]:
# 1. Definimos la lista con las columnas exactas que necesitas
columnas_deseadas = [
    'header_image',
    'required_age',
    'short_description',
    'appid',
    'metacritic_score'
]

# 2. Filtramos el DataFrame original y lo guardamos en data_limpia_img
df1 = df1[columnas_deseadas]

In [ ]:
# PASO 1: Extraer el ID numérico de la URL en data_limpia
# Esta línea busca el patrón "/app/números" y guarda solo los números en una nueva columna llamada 'appid'
data_limpia['appid'] = data_limpia['url'].str.extract(r'/app/(\d+)')

In [ ]:
# PASO 2: Estandarizar los tipos de datos
# Convertimos la columna 'appid' de AMBOS DataFrames a texto (string) para evitar errores de compatibilidad
data_limpia['appid'] = data_limpia['appid'].astype(str)
data_limpia_img['appid'] = data_limpia_img['appid'].astype(str)

# PASO 3: Unir ambos DataFrames
# Usamos pd.merge y le decimos que use 'appid' como la columna en común.
# how='inner' significa que solo conservará los juegos que existan en AMBAS tablas.
data_final = pd.merge(data_limpia, data_limpia_img, on='appid', how='inner')

In [33]:
df1[df1['required_age'].astype(str).str.contains('javascript', case=False, na=False)]

,appid,name,type,is_free,release_date,required_age,short_description,supported_languages,header_image,background,...,mat_pc_os_min,mat_pc_processor_min,mat_pc_memory_min,mat_pc_graphics_min,mat_pc_os_rec,mat_pc_processor_rec,mat_pc_memory_rec,mat_pc_graphics_rec,created_at,updated_at
166531,2731870,Ys X: Nordics,game,False,2024-10-25,javascript:ToggleCheckbox('checkbox_app_game_r...,"Explore uncharted islands, engage in fast-pace...","English<strong>*</strong>, Japanese<strong>*</...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,Windows 10/11,AMD Ryzen 5 1600,8 GB RAM,NVIDIA GeForce GTX 1050,Windows 10/11,Intel Core i5-10400,16 GB RAM,NVIDIA GeForce GTX 1650,2025-09-07 12:36:43.243384+00:00,2025-09-29 06:04:33.856771+00:00
194882,3189220,Ys X: Nordics - Legendary Cleria Armor & Raven...,dlc,True,2024-10-25,javascript:ToggleCheckbox('checkbox_app_game_r...,An exclusive cosmetics that changes Adol into ...,"English<strong>*</strong>, Japanese<strong>*</...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 12:36:43.243384+00:00,2025-09-29 02:01:37.107239+00:00
194883,3189230,Ys X: Nordics - Costume and Mana Promo Pack,dlc,False,2024-10-25,javascript:ToggleCheckbox('checkbox_app_game_r...,Includes the following items: An exclusive cos...,"English<strong>*</strong>, Japanese<strong>*</...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 12:36:43.243384+00:00,2025-09-29 02:01:37.107239+00:00
194884,3189240,Ys X: Nordics - Costume Pack,dlc,False,2024-10-25,javascript:ToggleCheckbox('checkbox_app_game_r...,A pack of DLC-exclusive cosmetics and attachme...,"English<strong>*</strong>, Japanese<strong>*</...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 12:36:43.243384+00:00,2025-09-29 02:01:37.107239+00:00
194885,3189250,Ys X: Nordics - Sandras Pack,dlc,False,2024-10-25,javascript:ToggleCheckbox('checkbox_app_game_r...,A pack of DLC-exclusive decor to dress the San...,"English<strong>*</strong>, Japanese<strong>*</...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 12:36:43.243384+00:00,2025-09-29 02:01:37.107239+00:00
194886,3189260,Ys X: Nordics - Attachment Pack,dlc,False,2024-10-25,javascript:ToggleCheckbox('checkbox_app_game_r...,"A pack of DLC-exclusive attachments, from eyew...","English<strong>*</strong>, Japanese<strong>*</...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 12:36:43.243384+00:00,2025-09-29 02:01:37.107239+00:00
194887,3189270,Ys X: Nordics - Starter Pack,dlc,False,2024-10-25,javascript:ToggleCheckbox('checkbox_app_game_r...,A pack of various items to start your adventur...,"English<strong>*</strong>, Japanese<strong>*</...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 12:36:43.243384+00:00,2025-09-29 02:01:37.107239+00:00
194888,3189280,Ys X: Nordics - Advanced Pack,dlc,False,2024-10-25,javascript:ToggleCheckbox('checkbox_app_game_r...,A pack of various items to give your adventure...,"English<strong>*</strong>, Japanese<strong>*</...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 12:36:43.243384+00:00,2025-09-29 02:01:37.107239+00:00
194889,3189290,Ys X: Nordics - Freebie Pack,dlc,True,2024-10-25,javascript:ToggleCheckbox('checkbox_app_game_r...,A complimentary trial set. The latter will lea...,"English<strong>*</strong>, Japanese<strong>*</...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 12:36:43.243384+00:00,2025-09-29 02:01:37.107239+00:00

In [32]:
df1[df1['required_age'].astype(str).str.contains('javascript', case=False, na=False)]['background'].iloc[0]

'https://store.akamai.steamstatic.com/images/storepagebackground/app/2731870?t=1755624013'

In [ ]:
    # Merge con segunda base de datos
df1 = df1[['header_image', 'required_age', 'short_description', 'appid', 'metacritic_score']].copy()

In [65]:
# Elimina el símbolo '+' de valores como '17+' para poder convertirlos a número
df1['required_age'] = df1['required_age'].astype(str).str.replace('+', '', regex=False)

# Convierte a número entero, los valores inválidos (javascript, texto) se reemplazan con 0
df1['required_age'] = pd.to_numeric(df1['required_age'], errors='coerce').fillna(0).astype(int)

# Si required_age es 0 se reemplaza con 'Para todas las edades',
# si tiene un número mayor se reemplaza con 'Juego para mayores de X'
df1['required_age'] = df1['required_age'].apply(
    lambda x: f"Para todas las edades" if x == 0 else f"Juego para mayores de {x} años"
)

# Estandarizamos appid a string en ambos DataFrames para evitar errores en el merge
df['appid'] = df['appid'].astype(str)
df1['appid'] = df1['appid'].astype(str)

# Unimos ambos DataFrames por appid, conservando solo los juegos presentes en ambas tablas
df = pd.merge(df, df1, on='appid', how='inner')

In [66]:
df

,url,name,release_date,popular_tags,game_details,languages,genre,game_description,original_price,review_percentage,appid,embedding,header_image,required_age,short_description,metacritic_score
0,https://store.steampowered.com/app/379720/DOOM/,DOOM,2016,"Tags populares: FPS, Gore, Action, Demons, Sho...","Tags populares: Single-player, Multi-player, C...","English, French, Italian, German, Spanish - Sp...",Genero de juego: Action,"about this game developed by id software, the ...",19.99,Porcentaje de recomendación de jugadores: 89%,379720,"about this game developed by id software, the ...",https://shared.akamai.steamstatic.com/store_it...,Juego para mayores de 17 años,Now includes all three premium DLC packs (Unto...,85.0
1,https://store.steampowered.com/app/578080/PLAY...,PLAYERUNKNOWN'S BATTLEGROUNDS,2017,"Tags populares: Survival, Shooter, Multiplayer...","Tags populares: Multi-player, Online Multi-Pla...","English, Korean, Simplified Chinese, French, G...","Genero de juego: Action, Adventure, Massively ...",about this game playerunknown's battlegrounds ...,29.99,Porcentaje de recomendación de jugadores: 49%,578080,about this game playerunknown's battlegrounds ...,https://shared.akamai.steamstatic.com/store_it...,Para todas las edades,"PUBG: BATTLEGROUNDS, the high-stakes winner-ta...",NaN
2,https://store.steampowered.com/app/637090/BATT...,BATTLETECH,2018,"Tags populares: Mechs, Strategy, Turn-Based, T...","Tags populares: Single-player, Multi-player, O...","English, French, German, Russian","Genero de juego: Action, Adventure, Strategy",about this game from original battletech/mechw...,39.99,Porcentaje de recomendación de jugadores: 54%,637090,about this game from original battletech/mechw...,https://shared.akamai.steamstatic.com/store_it...,Para todas las edades,Take command of your own mercenary outfit of '...,78.0
3,https://store.steampowered.com/app/221100/DayZ/,DayZ,2018,"Tags populares: Survival, Zombies, Open World,...","Tags populares: Multi-player, Online Multi-Pla...","English, French, Italian, German, Spanish - Sp...","Genero de juego: Action, Adventure, Massively ...",about this game the post-soviet country of che...,44.99,Porcentaje de recomendación de jugadores: 57%,221100,about this game the post-soviet country of che...,https://shared.akamai.steamstatic.com/store_it...,Juego para mayores de 17 años,How long can you survive a post-apocalyptic wo...,NaN
4,https://store.steampowered.com/app/8500/EVE_On...,EVE Online,2003,"Tags populares: Space, Massively Multiplayer, ...","Tags populares: Multi-player, Online Multi-Pla...","English, German, Russian, French","Genero de juego: Action, Free to Play, Massive...",about this game,0.00,Porcentaje de recomendación de jugadores: 54%,8500,"about this game\nGenero de juego: Action, Free...",https://shared.akamai.steamstatic.com/store_it...,Para todas las edades,EVE Online is a community driven space MMO whe...,88.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32308,https://store.steampowered.com/app/899836/Rock...,Rocksmith® 2014 Edition – Remastered – Sabaton...,2019,"Tags populares: Casual, Simulation","Tags populares: Single-player, Shared/Split Sc...","English, German, French, Italian, Spanish - Sp...","Genero de juego: Casual, Simulation","about this content play ""ghost division"" by sa...",2.99,NaN,899836,NaN,https://shared.akamai.steamstatic.com/store_it...,Para todas las edades,Play &quot;Ghost Division&quot; by Sabaton on ...,NaN
32309,https://store.steampowered.com/app/899832/Rock...,Rocksmith® 2014 Edition – Remastered – Stone T...,2019,"Tags populares: Casual, Simulation","Tags populares: Single-player, Shared/Split Sc...","English, German, French, Italian, Spanish - Sp...","Genero de juego: Casual, Simulation","about this content play ""trippin’ on a hole in...",2.99,NaN,899832,NaN,https://shared.akamai.steamstatic.com/store_it...,Para todas las edades,Play &quot;Trippin’ on a Hole in a Paper Heart...,NaN
32310,https://store.steampowered.com/app/906840/Fant...,Fantasy Grounds - Quests of Doom 4: A Midnight...,2018,"Tags populares: RPG, Indie, Strategy, Software...","Tags populares: Multi-player, Co-op, Cross-Pla...",English,"Genero de juego: Indie, RPG, Strategy",about this content quests of doom 4: a midnigh...,7.99,NaN,906840,NaN,https://shared.akamai.steamstatic.com/store_it...,Para todas las edades,Quests of Doom 4: A Midnight Council of Quailb...,NaN
32311,https://store.steampowered.com/app/906635/Mega...,Mega Man X5 Sound Collection,2018,Tags populares: Action,"Tags populares: Single-player, Downloadable Co...","English, French, Italian, German, Spanish - Sp...",Genero de juego: Action,about this content get equipped with the stunn...,9.99,NaN,906635,NaN,https://shared.akamai.steamstatic.com/store_it...,Para todas las edades,Get equipped with the stunningly nostalgic Meg...,NaN
32312,https://store.steampowered.com/app/908000/Stor...,Stories In Stone,2018,"Tags populares: RPG, Adventure","Tags populares: Single-player, Partial Control...",English,"Genero de juego: Adventure, RPG",about this game an rpg about a tribe exploring...,4.99,NaN,908000,NaN,https://shared.akamai.steamstatic.com/store_it...,Para todas las edades,An RPG about a tribe exploring an ancient worl...,NaN

In [60]:
import sys
sys.path.append('../game_on/')

from pln_model.limpieza import limpieza

In [61]:
import os
path = os.path.join(os.path.dirname(os.path.abspath('__file__')), '..', 'raw_data', 'steam_games.csv')
df = pd.read_csv(path)

In [62]:
df = limpieza(df)

In [44]:
df.columns

Index(['url', 'name', 'release_date', 'popular_tags', 'game_details',
       'languages', 'genre', 'game_description', 'original_price',
       'review_percentage', 'appid', 'embedding'],
      dtype='object')

In [167]:
df1['embedding'].iloc[0]

'about this game developed by id software, the studio that pioneered the first-person shooter genre and created multiplayer deathmatch, doom returns as a brutally fun and challenging modern-day shooter experience. relentless demons, impossibly destructive guns, and fast, fluid movement provide the foundation for intense, first-person combat – whether you’re obliterating demon hordes through the depths of hell in the single-player campaign, or competing against your friends in numerous multiplayer modes. expand your gameplay experience using doom snapmap game editor to easily create, play, and share your content with the world. story: you’ve come here for a reason. the union aerospace corporation’s massive research facility on mars is overwhelmed by fierce and powerful demons, and only one person stands between their world and ours. as the lone doom marine, you’ve been activated to do one thing – kill them all. key features: a relentless campaign there is no taking cover or stopping to regenerate health as you beat back hell’s raging demon hordes. combine your arsenal of futuristic and iconic guns, upgrades, movement and an advanced melee system to knock-down, slash, stomp, crush, and blow apart demons in creative and violent ways. return of id multiplayer dominate your opponents in doom’s signature, fast-paced arena-style combat. in both classic and all-new game modes, annihilate your enemies utilizing your personal blend of skill, powerful weapons, vertical movement, and unique power-ups that allow you to play as a demon. endless possibilities doom snapmap – a powerful, but easy-to-use game and level editor – allows for limitless gameplay experiences on every platform. without any previous experience or special expertise, any player can quickly and easily snap together and visually customize maps, add pre-defined or completely custom gameplay, and even edit game logic to create new modes. instantly play your creation, share it with a friend, or make it available to players around the world – all in-game with the push of a button.\nGenero de juego: Action\nTags populares: FPS, Gore, Action, Demons, Shooter, First-Person, Great Soundtrack, Multiplayer, Singleplayer, Fast-Paced, Sci-fi, Horror, Classic, Atmospheric, Difficult, Blood, Remake, Zombies, Co-op, Memes\nTags populares: Single-player, Multi-player, Co-op, Steam Achievements, Steam Trading Cards, Partial Controller Support, Steam Cloud\nPorcentaje de recomendación de jugadores: 89%'

In [ ]:
from IPython.display import display, HTML
display(HTML(f"<p style='width:600px; word-wrap:break-word;'>{df1['embedding'].iloc[0]}</p>"))

In [ ]:
df['columna'].str.extract(r'/app/(\d+)/')

In [170]:
import os
path = os.path.join(os.path.dirname(os.path.abspath('__file__')), '..', 'raw_data', 'steam_games.csv')
df1 = pd.read_csv(path)
data_limpia = limpieza(df1)

In [120]:
from sentence_transformers import SentenceTransformer, util
import torch

# 1. Configuración del Modelo
# Usamos un modelo balanceado entre velocidad y precisión
model_name = 'all-MiniLM-L6-v2'
model = SentenceTransformer(model_name)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2900.24it/s]

In [134]:
data_limpia.columns.tolist()

['url',
 'name',
 'release_date',
 'popular_tags',
 'game_details',
 'languages',
 'genre',
 'game_description',
 'original_price',
 'review_percentage',
 'embedding']

In [171]:
data_limpia= data_limpia.head(10)
data_limpia = data_limpia.dropna(subset=['embedding'])

In [136]:
data_limpia['embedding'].isna().sum()

np.int64(0)

In [172]:
# 1. Primero encodear el texto a vectores numéricos
game_embeddings = model.encode(data_limpia['embedding'].tolist(), convert_to_tensor=True)

In [173]:
query = "juego de acción multijugador"
query_embedding = model.encode(query, convert_to_tensor=True)

In [ ]:
# 2. Cálculo de similitud coseno
cosine_scores = util.cos_sim(query_embedding, game_embeddings)[0]

In [ ]:
# 3. Obtener los mejores N resultados
n_top = 5
top_results = torch.topk(cosine_scores, k=n_top)

In [142]:
# 4. Obtener los mejores N resultados
n_top = 5
top_results = torch.topk(cosine_scores, k=n_top)

In [143]:

# 5. Mostrar resultados
print(f"🔎 Resultados para: '{query}'\n")
print("="*50)

for score, idx in zip(top_results.values, top_results.indices):
    game = data_limpia.iloc[idx.item()]
    print(f"🎮 JUEGO: {game['name']}")
    print(f"📊 Match: {score:.2%}")
    print(f"📂 Género: {game['genre']}")
    print(f"tags: {game['popular_tags']}")
    print(f"💰 Precio: {game['original_price']}")
    print(f"⭐ Reviews: {game['review_percentage']}")
    print(f"🔗 Link: {game['url']}")
    print("-" * 50)

🔎 Resultados para: 'juego de acción multijugador'

==================================================
🎮 JUEGO: EVE Online
📊 Match: 44.01%
📂 Género: Genero de juego: Action, Free to Play, Massively Multiplayer, RPG, Strategy
tags: Tags populares: Space, Massively Multiplayer, Sci-fi, Sandbox, MMORPG, Open World, RPG, PvP, Multiplayer, Free to Play, Economy, Strategy, Space Sim, Simulation, Action, Difficult, Tactical, Capitalism, PvE, Atmospheric
💰 Precio: 0.0
⭐ Reviews: Porcentaje de recomendación de jugadores: 54%
🔗 Link: https://store.steampowered.com/app/8500/EVE_Online/
--------------------------------------------------
🎮 JUEGO: PLAYERUNKNOWN'S BATTLEGROUNDS
📊 Match: 23.08%
📂 Género: Genero de juego: Action, Adventure, Massively Multiplayer
tags: Tags populares: Survival, Shooter, Multiplayer, Battle Royale, PvP, FPS, Third-Person Shooter, Action, Online Co-Op, Tactical, Co-op, First-Person, Early Access, Strategy, Competitive, Third Person, Team-Based, Difficult, Simulation, Stealth
💰 Precio: 29.99
⭐ Reviews: Porcentaje de recomendación de jugadores: 49%
🔗 Link: https://store.steampowered.com/app/578080/PLAYERUNKNOWNS_BATTLEGROUNDS/
--------------------------------------------------
🎮 JUEGO: Devil May Cry 5
📊 Match: 11.72%
📂 Género: Genero de juego: Action
tags: Tags populares: Action, Hack and Slash, Great Soundtrack, Demons, Character Action Game, Spectacle fighter, Third Person, Violent, Singleplayer, Classic, Stylized, Gore, Story Rich, Nudity, Multiplayer, Controller, Difficult, Adventure, Anime, Family Friendly
💰 Precio: 59.99
⭐ Reviews: Porcentaje de recomendación de jugadores: 87%
🔗 Link: https://store.steampowered.com/app/601150/Devil_May_Cry_5/
--------------------------------------------------
🎮 JUEGO: BATTLETECH
📊 Match: 7.44%
📂 Género: Genero de juego: Action, Adventure, Strategy
tags: Tags populares: Mechs, Strategy, Turn-Based, Turn-Based Tactics, Sci-fi, Turn-Based Strategy, Tactical, Singleplayer, Robots, RPG, Action, Multiplayer, Futuristic, Character Customization, Management, Adventure, Space, Story Rich, Great Soundtrack, Difficult
💰 Precio: 39.99
⭐ Reviews: Porcentaje de recomendación de jugadores: 54%
🔗 Link: https://store.steampowered.com/app/637090/BATTLETECH/
--------------------------------------------------
🎮 JUEGO: They Are Billions
📊 Match: 3.61%
📂 Género: Genero de juego: Strategy, Early Access
tags: Tags populares: Early Access, Base Building, Strategy, Zombies, Survival, RTS, Steampunk, City Builder, Tower Defense, Post-apocalyptic, Building, Singleplayer, Resource Management, Real-Time with Pause, Early Access, Difficult, Tactical, Management, Indie, Isometric
💰 Precio: 29.99
⭐ Reviews: Porcentaje de recomendación de jugadores: 83%
🔗 Link: https://store.steampowered.com/app/644930/They_Are_Billions/
--------------------------------------------------

In [ ]:
from sentence_transformers import SentenceTransformer, util
import torch

# 1. Configuración del Modelo
# Usamos un modelo balanceado entre velocidad y precisión
model_name = 'all-MiniLM-L6-v2'
model = SentenceTransformer(model_name)

# 2. Simulación de Datos (Basado en el dataset de Steam de Kaggle)
# Cuando el equipo de datos te pase el CSV, cambiaremos esto por pd.read_csv()
data = {
    'game_id': [1, 2, 3, 4, 5],
    'title': ['Left 4 Dead 2', 'Stardew Valley', 'Elden Ring', 'Portal 2', 'Cyberpunk 2077'],
    'description': [
        'Zombies apocalypse cooperative shooter.',
        'Country life RPG with farming and animals.',
        'Challenging action RPG in a dark fantasy world.',
        'Physics-based puzzle game with portals.',
        'Open world action RPG set in a futuristic city.'
    ],
    'tags': ['Action, Zombies, Co-op', 'Farming, Simulation, Relaxing', 'Souls-like, Difficult, RPG', 'Puzzle, Sci-fi, Funny', 'Cyberpunk, RPG, Open World']
}

df = pd.DataFrame(data)

# 3. Creación del "Vibe Text" (Adaptación sugerida)
# SBERT funciona mejor si combinamos la descripción con los tags
df['metadata_combined'] = df['title'] + " " + df['description'] + " " + df['tags']

# 4. Generación de Embeddings
print(f"Vectorizando {len(df)} juegos...")
game_embeddings = model.encode(df['metadata_combined'].tolist(), convert_to_tensor=True)

# 5. Función de Recomendación Adaptada
def get_recommendations(user_query, n_top=3):
    # Vectorizar la consulta del usuario
    query_embedding = model.encode(user_query, convert_to_tensor=True)

    # Calcular similitud coseno
    cosine_scores = util.cos_sim(query_embedding, game_embeddings)[0]

    # Obtener los mejores N resultados
    top_results = torch.topk(cosine_scores, k=n_top)

    print(f"--- Recomendaciones para: '{user_query}' ---\n")
    for score, idx in zip(top_results.values, top_results.indices):
        game = df.iloc[idx.item()]
        print(f"🎯 Juego: {game['title']}")
        print(f"📊 Similitud: {score:.4f}")
        print(f"📝 Tags: {game['tags']}")
        print("-" * 40)

# PRUEBA DE FUNCIONAMIENTO
get_recommendations("I want a difficult game with magic and swords")

In [131]:
query_embeddings = model.encode(data_limpia['embedding'].tolist(), convert_to_tensor=True)

In [ ]:
# 2. Preparación de los Embeddings
# Si la columna 'embedding' ya tiene los vectores, los convertimos a un Tensor de PyTorch
# Si no están procesados, descomenta la línea de abajo para generarlos:
# game_embeddings = model.encode(data_limpia['game_description'].tolist(), convert_to_tensor=True)

# Asumiendo que 'embedding' ya existe y es una lista de listas o arrays:
game_embeddings = torch.tensor(data_limpia['embedding'].tolist())

# 3. Función de Recomendación Adaptada a tus columnas
def recomendador_game_on(query, n_top=5):
    # Vectorizamos la duda del usuario
    query_embedding = model.encode(query, convert_to_tensor=True)

    # Cálculo de similitud coseno
    cosine_scores = util.cos_sim(query_embedding, game_embeddings)[0]

    # Buscamos los mejores N
    top_results = torch.topk(cosine_scores, k=n_top)

    print(f"🔎 Resultados para: '{query}'\n")
    print("="*50)

    for score, idx in zip(top_results.values, top_results.indices):
        game = data_limpia.iloc[idx.item()]

        print(f"🎮 JUEGO: {game['name']}")
        print(f"📊 Match: {score:.2%}")
        print(f"📂 Género: {game['genre']}")
        print(f"tags: {game['popular_tags']}")
        print(f"💰 Precio: {game['original_price']}")
        print(f"⭐ Reviews: {game['review_percentage']}")
        print(f"🔗 Link: {game['url']}")
        print("-" * 50)

# 4. Prueba del modelo con tu data real
recomendador_game_on("I want a strategy game about space and aliens")